version: '3.8'

services:
  movies:
    build:
      context: .
      args:
        SERVICE_NAME: movies
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    build:
      context: .
      args:
        SERVICE_NAME: train
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    build:
      context: .
      args:
        SERVICE_NAME: recharge
    ports:
      - "83:80"
    deploy:
      replicas: 3
