version: '3.8'

services:
  movies:
    image: mmohit1271/paytmmovie:latest  # Use the correct image reference
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: mmohit1271/paytmtrain:latest  # Use the correct image reference
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: mmohit1271/paytmrecharge:latest  # Use the correct image reference
    ports:
      - "83:80"
    deploy:
      replicas: 3
