version: '3.8'

services:
  movies:
    images: mmohit1271/paytmmovie:latest
    port:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: mmohit1271/paytmtrain:latest
    port:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: mmohit1271/paytmrecharge:latest
    port:
      - "83:80"
    deploy:
      replicas: 3
